# Render Blueprint for PharmaLink Next.js Application
services:
  - type: web
    name: pharmalink
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: pharmalink
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: pharmalink-db
          property: connectionString
    domains:
      - pharmalink.onrender.com

databases:
  - name: pharmalink-db
    databaseName: pharmalink
    user: pharmalink_user
    plan: free
